name: 'Flyway Postgres Migration'
description: 'Run migrations using your Github Action'
inputs:
  flyway_conf_sha:
    description: 'Flyway Configuration in Base64'
    required: true
    default: ''
  flyway_sql:
    description: 'Flyway SQL path'
    required: false
    default: './flyway/sql'
  pre_migration_bash_sha:
    description: 'Bash file in base64 to run before migration'
    required: false
    default: ''
  post_migration_bash_sha:
    description: 'Bash file in base64 to run after migration'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
